# Generated by Django 3.0.4 on 2020-04-06 16:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(max_length=500)),
                ('visibility', models.CharField(choices=[('PRV', 'Private'), ('PUB', 'Public')], default='PRV', max_length=3)),
                ('file', models.FileField(upload_to='user_files', validators=[files.models.validate_file_extension])),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
