# Generated by Django 3.0.4 on 2020-04-06 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20200406_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='tag',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='tag',
            field=models.ManyToManyField(to='files.Tag'),
        ),
    ]
