# Generated by Django 3.0.4 on 2020-04-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_auto_20200407_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='sha512_hash',
            field=models.CharField(default='Hash', max_length=100),
        ),
    ]
