# Generated by Django 3.0.4 on 2020-04-07 23:16

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_auto_20200407_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(upload_to='user-files', validators=[files.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='sha512_file_hash',
            field=models.CharField(default='Hash', max_length=200),
        ),
    ]
